import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "GeoExplorer",
  description: "Generated by create next app",
  icons:{
    icon: ['/favicon.ico?v=4'],
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="emerald">
      <body className={rubik.className}>

        <main>
          {children}
        </main>
        </body>
    </html>
  );
}
